import { Inter } from "next/font/google";
import "./globals.css";

import { UserProvider } from "@auth0/nextjs-auth0/client";

import PrelineScript from "@/components/PrelineScript";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <UserProvider>
        <body
          className={`
          min-h-screen bg-background font-sans antialiased ${inter.className}
          `}
        >
          <Navbar />
          {children}
          {/* <Footer /> */}
        </body>
      </UserProvider>
      <PrelineScript />
    </html>
  );
}
