import { Inter } from "next/font/google";
import "./globals.css";

import { UserProvider } from "@auth0/nextjs-auth0/client";

import PrelineScript from "@/components/PrelineScript";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <UserProvider>
        <body
          className={`
          min-h-screen font-sans antialiased ${inter.className}
          `}
        >
          <div className="fixed left-0 top-0 -z-10 h-full w-full">
            <div className="relative h-full w-full bg-white">
              <div className="absolute h-full w-full bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px] [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)]"></div>
            </div>
          </div>

          <Navbar />
          {children}
          {/* <Footer /> */}
        </body>
      </UserProvider>
      <PrelineScript />
    </html>
  );
}
