import { Inter as FontSans } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import PrelineScript from "@/components/PrelineScript";

import { cn } from "@/lib/utils";

import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          {children}
        </body>
        <PrelineScript />
      </UserProvider>
    </html>
  );
}
